import type { ListeningTrack } from "@/lib/listening-history";

/** Kept outside the data file regenerated by /admin. */
export type NowListening = ListeningTrack;
export interface NowReading {
  title: string;
  author: string;
  coverUrl?: string;
}
export interface Now {
  listening: NowListening;
  reading: NowReading;
}
